trigger: none  # Manual or scheduled trigger

variables:
  dockerHubUsername: 'your-dockerhub-username'
  imageName: 'your-image-name'
  tag: 'latest'  # Or use a specific version

stages:
- stage: Deploy
  displayName: 'Deploy Docker Container'
  jobs:
  - job: Deploy
    displayName: 'Deploy Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'DockerHub'

    - script: |
        docker pull $(dockerHubUsername)/$(imageName):$(tag)
        docker run -d -p 8080:80 $(dockerHubUsername)/$(imageName):$(tag)
      displayName: 'Run Docker Container'
