trigger:
  branches:
    include: [ main ]

stages:
- stage: Deploy
  jobs:
  - job: deployToACI
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'myAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group my-rg \
            --name ml-server \
            --image <your_acr>.azurecr.io/ml-api:latest \
            --registry-login-server <your_acr>.azurecr.io \
            --cpu 1 --memory 1 \
            --dns-name-label mlserver-$(Build.BuildId) \
            --ports 5000
